version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest
        environment:
          XOOS_TEST: psql://root@localhost/circleci 
      - image: circleci/postgres:9.6.5-alpine-ram

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              apt install -y postgresql-client
              zef install --deps-only .
      - run:
          name: test 
          command: |
              psql -d $XOOS_TEST < ./sql/tests.sql
              zef test .
